frameworkVersion: ">=1.2.1"

service: tensorflow-lambda-regression

provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: us-west-2

<<<<<<< HEAD
package:
  exclude:
    - .git/**
    - .serverless/**

=======
>>>>>>> 8bdc8fa56a8a98c32c221dcda44867aae4c43431
functions:
  predict:
    handler: handler.predict
    events:
      - http:
          path: /predict
          method: post

